baseURL = 'http://www.fairplayers.fr'
languageCode = 'fr-fr'
resourceDir = "../resources"
title = 'fairplayers'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "fr"
enableRobotsTXT = true
Paginate = 10
recent_posts_number = 3
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.fr]
    weight = 2
    contentDir = "content"

[params]
  description = "L'association des joueurs et joueuses de jeux video de Betton."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  date_format = "2 January 2006"

[[params.ananke_socials]]
name = "discord"
url = "https://discord.gg/vDVT485T"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/fairplayers_fr"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/fairplayers"
